Name:           perl-Net-Prometheus
Version:        0.07
Release:        1%{?dist}
Summary:        Export monitoring metrics for prometheus
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-Prometheus/
Source0:        http://www.cpan.org/authors/id/P/PE/PEVANS/Net-Prometheus-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(List::Util) >= 1.29
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Ref::Util)
BuildRequires:  perl(Struct::Dumb)
BuildRequires:  perl(Test::Fatal)
BuildRequires:  perl(Test::More) >= 0.88
Requires:       perl(List::Util) >= 1.33
Requires:       perl(Ref::Util)
Requires:       perl(Struct::Dumb)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides the ability for a program to collect monitoring
metrics and export them to the prometheus.io monitoring server.

%prep
%setup -q -n Net-Prometheus-%{version}

%build
%{__perl} Build.PL --installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install --destdir=$RPM_BUILD_ROOT --create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes examples LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Mar 12 2019 Michal Ingeli <mi@v3.sk> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
