Name:           perl-Net-Bonjour
Version:        0.96
Release:        1%{?dist}
Summary:        Module for DNS service discovery (Apple's Bonjour)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-Bonjour/
Source0:        http://www.cpan.org/modules/by-module/Net/Net-Bonjour-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Net::DNS) >= 0.5
BuildRequires:  perl(Socket) >= 1.75
BuildRequires:  perl(Test::More)
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators

Requires:       perl(Net::DNS) >= 0.5
Requires:       perl(Socket) >= 1.75
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Net::Bonjour is a set of modules that allow one to discover local services
via multicast DNS (mDNS) or enterprise services via traditional DNS. This
method of service discovery has been branded as Bonjour by Apple Computer.

%prep
%setup -q -n Net-Bonjour-%{version}

%build
yes n | %{__perl} Makefile.PL INSTALLDIRS=vendor 
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Sep 20 2018 Michal Ingeli <mi@v3.sk> 0.96-2
- Added perl-{generators,interpreter} BR

* Fri Aug 31 2018 Michal Ingeli <mi@v3.sk> 0.96-1
- Specfile autogenerated by cpanspec 1.78.
