Name:           perl-OpenCL
Version:        1.01
Release:        2%{?dist}
Summary:        Open Computing Language Bindings
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/OpenCL/
Source0:        http://www.cpan.org/authors/id/M/ML/MLEHMANN/OpenCL-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(Async::Interrupt) >= 1.1
BuildRequires:  perl(common::sense) >= 3
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  gcc
BuildRequires:  perl-devel
BuildRequires:  perl-interpreter
BuildRequires:  perl-generators
Buildrequires:  opencl-headers
Buildrequires:  ocl-icd-devel
Requires:       perl(Async::Interrupt) >= 1.1
Requires:       perl(common::sense) >= 3
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is an early release which might be useful, but hasn't seen much
testing.

%prep
%setup -q -n OpenCL-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS" <<<yes n
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes COPYING gengetinfo getinfo.txt h_extract META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/OpenCL*
%{_mandir}/man3/*

%changelog
* Wed Sep 19 2018 Michal Ingeli <mi@v3.sk> 1.01-2
- Added perl and gcc BR

* Wed Sep 19 2018 Michal Ingeli <mi@v3.sk> 1.01-1
- Specfile autogenerated by cpanspec 1.78.
