Name:           perl-IO-stringy
Version:        2.111
Release:        2%{?dist}
Summary:        IO::stringy Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/IO-stringy/
Source0:        http://www.cpan.org/modules/by-module/IO/IO-stringy-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
SYNOPSIS        IO::
::AtomicFile   adpO  Write a file which is updated atomically     ERYQ
::Lines        bdpO  I/O handle to read/write to array of lines   ERYQ
::Scalar       RdpO  I/O handle to read/write to a string         ERYQ
::ScalarArray  RdpO  I/O handle to read/write to array of scalars ERYQ
::Wrap         RdpO  Wrap old-style FHs in standard OO interface  ERYQ
::WrapTie      adpO  Tie your handles & retain full OO interface  ERYQ

%prep
%setup -q -n IO-stringy-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc COPYING README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Sep 20 2018 Michal Ingeli <mi@v3.sk> 2.111-2
- Added perl-{generators,interpret}

* Thu Aug 30 2018 Michal Ingeli <mi@v3.sk> 2.111-1
- Specfile autogenerated by cpanspec 1.78.
